language: python
python:
  - 2.7

install:
 - $(which echo) -e "[buildout]\nextends = buildout.d/travis.cfg" > buildout.cfg
 - make .installed.cfg

script:
 - make coverage

after_success:
  - pip install python-coveralls==2.4.0
  - coveralls
